-- AlterTable
ALTER TABLE `Action` MODIFY `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `businessDate` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Company` MODIFY `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `User` MODIFY `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
